// Code generated by "stringer -type State"; DO NOT EDIT.

package process

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StateUnauthorized-0]
	_ = x[StateBase-1]
	_ = x[StateBasic-2]
	_ = x[StateAuthenticated-3]
	_ = x[StateSudo-4]
}

const _State_name = "StateUnauthorizedStateBaseStateBasicStateAuthenticatedStateSudo"

var _State_index = [...]uint8{0, 17, 26, 36, 54, 63}

func (i State) String() string {
	if i >= State(len(_State_index)-1) {
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
